In [49]:
import pandas as pd
import os
import glob
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

In [50]:
#combining no of csv file into one file with name combine_csv
os.chdir('D:\Lila\RTT-Points')
extension='csv'

all_filenames=[i for i in glob.glob('*.{}'.format(extension))]

combined_csv=pd.concat([pd.read_csv(f) for f in all_filenames])
df=combined_csv

In [51]:
df1=df.assign(Product_RTT=df['AP1RTT']*df['AP2RTT']*df['AP3RTT'])
df1

AP1RTT  AP1STDEV  AP1RSS  AP2RTT  AP2STDEV  AP2RSS  AP3RTT  AP3STDEV  \
0      7.789     0.371   -61.0   1.311     0.082     -47  11.037     1.192   
1      7.731     0.277   -61.0   0.999     0.186     -47  10.452     0.256   
2      7.731     0.442   -61.0   1.155     0.171     -47   9.368     0.661   
3      7.672     0.698   -62.0   1.194     0.206     -47   9.709     1.533   
4      7.643     2.609   -63.0   1.038     0.151     -46   9.748     2.350   
...      ...       ...     ...     ...       ...     ...     ...       ...   
1115   7.232     0.465   -60.0  12.825     0.293     -72   0.491     0.989   
1116   6.969     1.224   -62.0  13.528     0.637     -71   0.569     0.938   
1117   6.764     2.843   -64.0  11.389     1.182     -69   0.608     0.874   
1118   6.241     0.865   -54.0  10.178     0.968     -67   0.373     1.017   
1119   6.578     0.594   -58.0  10.452     0.593     -66   0.451     1.026   

      AP3RSS  x  y  Product_RTT  
0        -74  1  1   112.702990  
1        -72  1  1    80.723608  
2        -69  1  1    83.649729  
3        -67  1  1    88.938013  
4        -70  1  1    77.335115  
...      ... .. ..          ...  
1115     -51  6  8    45.540446  
1116     -51  6  8    53.643404  
1117     -51  6  8    46.837399  
1118     -51  6  8    23.693295  
1119     -51  6  8    31.007718  

[41187 rows x 12 columns]

In [52]:
df2=df1.assign(Product_STDEV=df1['AP1STDEV']*df1['AP2STDEV']*df1['AP3STDEV'])
df2

AP1RTT  AP1STDEV  AP1RSS  AP2RTT  AP2STDEV  AP2RSS  AP3RTT  AP3STDEV  \
0      7.789     0.371   -61.0   1.311     0.082     -47  11.037     1.192   
1      7.731     0.277   -61.0   0.999     0.186     -47  10.452     0.256   
2      7.731     0.442   -61.0   1.155     0.171     -47   9.368     0.661   
3      7.672     0.698   -62.0   1.194     0.206     -47   9.709     1.533   
4      7.643     2.609   -63.0   1.038     0.151     -46   9.748     2.350   
...      ...       ...     ...     ...       ...     ...     ...       ...   
1115   7.232     0.465   -60.0  12.825     0.293     -72   0.491     0.989   
1116   6.969     1.224   -62.0  13.528     0.637     -71   0.569     0.938   
1117   6.764     2.843   -64.0  11.389     1.182     -69   0.608     0.874   
1118   6.241     0.865   -54.0  10.178     0.968     -67   0.373     1.017   
1119   6.578     0.594   -58.0  10.452     0.593     -66   0.451     1.026   

      AP3RSS  x  y  Product_RTT  Product_STDEV  
0        -74  1  1   112.702990       0.036263  
1        -72  1  1    80.723608       0.013190  
2        -69  1  1    83.649729       0.049960  
3        -67  1  1    88.938013       0.220427  
4        -70  1  1    77.335115       0.925804  
...      ... .. ..          ...            ...  
1115     -51  6  8    45.540446       0.134746  
1116     -51  6  8    53.643404       0.731347  
1117     -51  6  8    46.837399       2.937012  
1118     -51  6  8    23.693295       0.851554  
1119     -51  6  8    31.007718       0.361400  

[41187 rows x 13 columns]

In [60]:
# Extract the last two columns as the output data
#output_data = df.iloc[:, -2:]
output_data = df2[['x','y']]


# Extract the remaining  columns as the input data
input_data = df2[['AP1RTT','AP1STDEV' ,'AP2RTT','AP2STDEV','AP3RTT','AP3STDEV','Product_RTT','Product_STDEV']]
#input_data = df.iloc[:,:-2]
np.set_printoptions(suppress=True) #to remove scientific notation

In [61]:
input_data=input_data.values
output_data=np.array(output_data.values)
print(output_data)
print('----------------------------------------')
print(input_data)
output_data.shape

[[1 1]
 [1 1]
 [1 1]
 ...
 [6 8]
 [6 8]
 [6 8]]
----------------------------------------
[[  7.789        0.371        1.311      ...   1.192      112.70299002
    0.03626302]
 [  7.731        0.277        0.999      ...   0.256       80.72360759
    0.01318963]
 [  7.731        0.442        1.155      ...   0.661       83.64972924
    0.0499597 ]
 ...
 [  6.764        2.843       11.389      ...   0.874       46.83739917
    2.93701232]
 [  6.241        0.865       10.178      ...   1.017       23.69329495
    0.85155444]
 [  6.578        0.594       10.452      ...   1.026       31.00771846
    0.36140029]]


(41187, 2)

In [66]:
from sklearn.preprocessing import OneHotEncoder

# Create a one-hot encoder object
one_hot_encoder = OneHotEncoder()

# Fit and transform the one-hot encoder on your output data
#output_data = np.array(output_data)
encoded_output = one_hot_encoder.fit_transform(output_data)
# Convert the encoded output data to a NumPy array format
#encoded_output = np.array(encoded_output)
encoded_output = encoded_output.toarray()
print(encoded_output)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [67]:
print(encoded_output.shape)
print(input_data.shape)

(41187, 14)
(41187, 8)


In [34]:
X=input_data
y=encoded_output
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 


In [36]:
X_train

array([[-0.91694578, -0.33523253, -0.28325493, ...,  0.21861253,
        -0.36797098, -0.14605958],
       [ 1.21872651, -1.14438563,  1.19427063, ..., -0.74741011,
         2.06107242, -0.55594092],
       [-0.49736124,  1.06396064,  0.31792048, ...,  0.07832616,
        -0.66918315, -0.17982199],
       ...,
       [ 1.28641544, -1.15847147,  1.22921345, ..., -0.75096166,
         2.19224062, -0.55843581],
       [ 0.51536918,  2.09848713, -2.00895396, ..., -1.11499593,
        -0.96200643, -0.536626  ],
       [-1.7092533 , -0.57938705,  0.86866704, ...,  0.10851436,
        -0.82834281, -0.44480467]])

In [37]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [47]:
# importing the libraries
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from sklearn.metrics import mean_squared_error
from keras.optimizers import SGD
from keras.optimizers import Adam


optimizer = Adam(learning_rate=0.0001)
#optimizer = SGD(learning_rate=0.01)

# create DNN model
model = Sequential()
 
# Input layer 
model.add(Dense(128, activation='relu', input_shape=(8,)))
 
# the Second layer of the model
model.add(Dense(units=200, kernel_initializer='normal', activation='relu'))
#model.add(Dropout(0.2))

# the third layer of the model
model.add(Dense(units=200, kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.2))

# the fourth layer of the model
model.add(Dense(units=128, kernel_initializer='normal', activation='relu'))
#model.add(Dropout(0.2)) 


# output layer with two outputs
model.add(Dense(14, activation='softmax'))
 
# Compiling the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
 
model.summary() 


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 128)               1152      
                                                                 
 dense_11 (Dense)            (None, 200)               25800     
                                                                 
 dense_12 (Dense)            (None, 200)               40200     
                                                                 
 dropout_2 (Dropout)         (None, 200)               0         
                                                                 
 dense_13 (Dense)            (None, 128)               25728     
                                                                 
 dense_14 (Dense)            (None, 14)                1806      
                                                                 
Total params: 94,686
Trainable params: 94,686
Non-trai

In [43]:
from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=3)
callbacks_list=[early_stopping]

In [44]:
n_epochs=20
history = model.fit(X_train, y_train, epochs=n_epochs, batch_size=32, validation_split=0.2,callbacks=callbacks_list)

Epoch 1/20
824/824 [==============================] - 5s 5ms/step - loss: 6901118.0000 - accuracy: 0.0990 - val_loss: 33513378.0000 - val_accuracy: 0.0000e+00
Epoch 2/20
824/824 [==============================] - 4s 5ms/step - loss: 193513296.0000 - accuracy: 0.0917 - val_loss: 570486080.0000 - val_accuracy: 0.1958
Epoch 3/20
824/824 [==============================] - 4s 5ms/step - loss: 991686464.0000 - accuracy: 0.0936 - val_loss: 1448256384.0000 - val_accuracy: 0.1351
Epoch 4/20
824/824 [==============================] - 4s 5ms/step - loss: 2983394304.0000 - accuracy: 0.0939 - val_loss: 3875168768.0000 - val_accuracy: 0.2102
